### ISSUE TITLE
Perte de mes articles

### ISSUE THREAD

**Issue by GuyliannEngels** [anaisbeauma/anais-beaumariage-blog#1]
Salut @anaisbeauma ,

J'utilise ton mail pour discuter de ton probleme de blog

> Bonsoir monsieur,
 Aujourd’hui, j’ai essayé d’accéder à RS studio afin de créer la section « My English activity » sur mon blog. J’ai remarqué que mes deux articles ne s’affichaient plus correctement sur le site (il ne reste que l’aperçu). J’ai récemment fait un tri dans les fichiers et j’ai dû en supprimer un qu’il ne fallait pas mais je ne sais pas lequel…
 J’ai donc essayé de régler le problème sur RS studio, seulement ce dernier ne reconnait plus mes identifiants GitHub.
Pouvez-vous m’aider ?
Merci d’avance.

**Comment by anaisbeauma** [comment]
Bonjour monsieur, 

Lors de mon dernier commit, j'ai fait un tri dans les dossiers du blog car il y en avait beaucoup de vide mais je pense avoir fait une fausse manœuvre et supprimé un dossier qu'il ne fallait pas.

J'ai réussi à récupérer mon accès à RS studio, je pense que je m'étais juste totalement déconnectée

**Comment by GuyliannEngels** [comment]
OK OK,

Je vois un peu le souci.
En local ton site ne me semble pas problématique

**Comment by anaisbeauma** [comment]
Oui, il s'affiche encore mais juste les aperçus... Alors que mes deux articles sont encore au complet quand je regarde le dossier dans RS studio

**Comment by GuyliannEngels** [comment]
Je vois d'où le probleme provient. Il ne me reste plus qu'à trouver une solution :p

**Comment by anaisbeauma** [comment]
Super, merci beaucoup !

**Comment by GuyliannEngels** [comment]
Si tu ouvres une fenêtre de navigation privée avec l'url de ton blog tout est rentré dans l'ordre.

Le problème provenait d'un accès à tes articles. En changeant le nom des dossiers contenant tes posts, tu as d'une certaine manière cassé le chemin d'accès.

J'ai corrigé cela.

ps: n'oublie pas de faire un pull
