### ISSUE TITLE
Affichage des nouveaux commits

### ISSUE THREAD

**Issue by anaisbeauma** [anaisbeauma/anais-beaumariage-blog#2]
Bonjour monsieur,

Depuis que vous avez réglé mon problème d'affichage de mes articles, j'ai l'impression que tous mes commits ne se répercutent pas sur le site. Je les ai pushé sur github, mais rien ne change sur la page web. 
J'ai fait 2 commits : la rédaction de "My English activity" et un autre sur la correction de l'orthographe sur mon article 2.

Merci d'avance !

**Comment by GuyliannEngels** [comment]
Salut @anaisbeauma ,

J'ai compilé tes différents fichiers que tu avais modifié et construis ton site. 
Je ne vois aucun problème particulier. 

Avais tu bien fais tes ***knit*** et ***Build website*** ?

Si tu  n'as plus de questions concernant cette issue, ferme cette dernière
